### PR TITLE
Fix edit should not edit nusnetid

### LINKED ISSUE #254: [PE-D][Tester F] Ambiguous instruction in UG when explaining how to navigate to the JAR file folder using `cd`
**Description:**  
The “Quick Start” section of the User Guide instructs users to  
> “Open a command terminal, using command `cd` + the path to get into the folder you put the jar file in...”  
However, the phrase “the path to get into the folder” can be confusing to users unfamiliar with command-line usage.  
It is unclear what “path” refers to or how to format it for their operating system (e.g., Windows vs macOS).

**Expected Behavior:**  
The UG should explicitly explain how to use the `cd` command

-------------
Labels: `severity.Medium` `type.DocumentationBug`

### PR DESCRIPTION
**Pull request by chuckyang123**
fixes #254

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -84,7 +84,12 @@ public CommandResult execute(Model model) throws CommandException {
         Person personToEdit = lastShownList.get(index.getZeroBased());
         Person editedPerson = createEditedPerson(personToEdit, editPersonDescriptor);
 
-        if (!personToEdit.isSamePerson(editedPerson) && model.hasPerson(editedPerson)) {
+        // Robust duplicate check: consider duplicates with others, but ignore the current target person
+        boolean duplicatesAnother = model.getAddressBook().getPersonList().stream()
+                .anyMatch(p -> !p.equals(personToEdit) && editedPerson.isSamePerson(p));
+        if (duplicatesAnother) {
+            logger.info(() -> String.format("Edit blocked due to duplicate with another person (target index=%d).",
+                    index.getOneBased()));
```
Comment (FisherSkyi) [inline src/main/java/seedu/address/logic/commands/EditCommand.java]: LGTM. Just notice that if the 5editable fields are name, nusnetid, email, telegram and phone. Then the new student will not equal personToEdit so current target person will be autoignored and no need to check seperately

**Review by broccoli0616 — APPROVED** [review]
